/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import javax.swing.JOptionPane;
import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.persistencia.ConexionBD;
import ticketwizard.persistencia.PersonasDAO;

/**
 *
 * @author PC
 */
public class FrmAgregarSaldo extends javax.swing.JFrame {

    ConexionBD conexionBD = new ConexionBD();
    private final ControlInicio control;
    private final PersonasDTO personasDTO;

    /**
     * Constructor que inicializa los atributos de la clase con el valor de sus
     * parametros
     *
     * @param control Clase control
     * @param personasDTO Persona que haya iniciado sesion en el programa
     */
    public FrmAgregarSaldo(ControlInicio control, PersonasDTO personasDTO) {
        initComponents();
        this.control = control;
        this.personasDTO = personasDTO;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtSaldoAgregar = new javax.swing.JTextField();
        btnAceptar = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JLabel();
        bgAgregarSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 750));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtSaldoAgregar, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, 170, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAceptar.png"))); // NOI18N
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 410, 98, 40));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 410, 98, 40));

        bgAgregarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgAgregarSaldo.png"))); // NOI18N
        getContentPane().add(bgAgregarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        FrmMiPerfilSaldo frmMiPerfilSaldo = new FrmMiPerfilSaldo(control, personasDTO);
        frmMiPerfilSaldo.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked
        PersonasDAO personasDAO = new PersonasDAO(conexionBD);

        try {
            personasDAO.agregarSaldo(personasDTO.getCodigoPersona(),
                    Double.parseDouble(txtSaldoAgregar.getText()));

            FrmMiPerfilSaldo frmMiPerfilSaldo = new FrmMiPerfilSaldo(control, personasDTO);
            frmMiPerfilSaldo.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.err.println("Ocurrio un problema al agregar el saldo: " + e);
        }

    }//GEN-LAST:event_btnAceptarMouseClicked

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmAgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmAgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmAgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmAgregarSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmAgregarSaldo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgAgregarSaldo;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JTextField txtSaldoAgregar;
    // End of variables declaration//GEN-END:variables
}
