/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.entidades.Eventos;

/**
 * Clase que muestra el catalogo de eventos
 *
 * @author PC
 */
public class FrmCatalogoEventos extends javax.swing.JFrame {

    private final ControlInicio control;
    private final PersonasDTO personasDTO;

    /**
     * Constructor que inicializa los atributos del frame al valor de sus
     * parametros
     *
     * @param control Clase control
     * @param personasDTO Perfil de la persona que inica sesion
     */
    public FrmCatalogoEventos(ControlInicio control, PersonasDTO personasDTO) {
        initComponents();
        this.control = control;
        this.personasDTO = personasDTO;
        llenarTablaEventos();
    }

    /**
     * Metodo que llena la tabla con todos los eventos
     */
    private void llenarTablaEventos() {
        List<Eventos> listaEventos = this.control.consultarListaEventos();
        DefaultTableModel model = (DefaultTableModel) this.tblEventos.getModel();
        for (Eventos evento : listaEventos) {
            Object[] filaTabla = {
                evento.getNombre(),
                evento.getDescripcion(),
                evento.getFechaHora()
            };
            model.addRow(filaTabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        btnClose = new javax.swing.JLabel();
        btnMiPerfil = new javax.swing.JLabel();
        btnVentaReventa = new javax.swing.JLabel();
        btnMisBoletos = new javax.swing.JLabel();
        btnEventos = new javax.swing.JLabel();
        bgCatalogoEventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "nombre", "descripcion", "fechaHora"
            }
        ));
        jScrollPane1.setViewportView(tblEventos);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 670, 490));

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 20));

        btnMiPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiPerfilMouseClicked(evt);
            }
        });
        getContentPane().add(btnMiPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 20));

        btnVentaReventa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentaReventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaReventaMouseClicked(evt);
            }
        });
        getContentPane().add(btnVentaReventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, 20));

        btnMisBoletos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMisBoletosMouseClicked(evt);
            }
        });
        getContentPane().add(btnMisBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 20));

        btnEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEventosMouseClicked(evt);
            }
        });
        getContentPane().add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 60, 20));

        bgCatalogoEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgCatalogoEventos.png"))); // NOI18N
        getContentPane().add(bgCatalogoEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMiPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiPerfilMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMiPerfilMouseClicked

    private void btnMisBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisBoletosMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnMisBoletosMouseClicked

    private void btnVentaReventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaReventaMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnVentaReventaMouseClicked

    private void btnEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventosMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEventosMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(CatalogoEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(CatalogoEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(CatalogoEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(CatalogoEventos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new CatalogoEventos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgCatalogoEventos;
    private javax.swing.JLabel btnClose;
    private javax.swing.JLabel btnEventos;
    private javax.swing.JLabel btnMiPerfil;
    private javax.swing.JLabel btnMisBoletos;
    private javax.swing.JLabel btnVentaReventa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblEventos;
    // End of variables declaration//GEN-END:variables
}
