/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.JTable;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableColumn;
import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.entidades.Eventos;

/**
 * Clase que muestra el catalogo de eventos
 *
 * @author PC
 */
public class FrmCatalogoEventos extends javax.swing.JFrame {

    private final ControlInicio control;
    private final PersonasDTO personasDTO;

    /**
     * Constructor que inicializa los atributos del frame al valor de sus
     * parametros
     *
     * @param control Clase control
     * @param personasDTO Perfil de la persona que inica sesion
     */
    public FrmCatalogoEventos(ControlInicio control, PersonasDTO personasDTO) {
        initComponents();
        this.control = control;
        this.personasDTO = personasDTO;
        llenarTablaEventos();
    }

    /**
     * Metodo que llena la tabla con todos los eventos
     */
    private void llenarTablaEventos() {
        List<Eventos> listaEventos = this.control.consultarListaEventos();
        DefaultTableModel model = (DefaultTableModel) this.tblEventos.getModel();
        for (Eventos evento : listaEventos) {
            Object[] filaTabla = {
                evento.getCodigoEvento(),
                evento.getNombre(),
                evento.getDescripcion(),
                evento.getFechaHora(),
                evento.getEstado(),
                evento.getCiudad(),
                evento.getCantidadAsientos()
            };
            model.addRow(filaTabla);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblEventos = new javax.swing.JTable();
        btnClose = new javax.swing.JLabel();
        btnMiPerfil = new javax.swing.JLabel();
        btnVentaReventa = new javax.swing.JLabel();
        btnMisBoletos = new javax.swing.JLabel();
        btnEventos = new javax.swing.JLabel();
        txtCodigoCompra = new javax.swing.JTextField();
        btnComprar = new javax.swing.JButton();
        lblBotonCompra = new javax.swing.JLabel();
        bgCatalogoEventos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblEventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "codigo", "nombre", "descripcion", "fechaHora", "Estado", "Ciudad", "Cantidad Asientos"
            }
        ));
        tblEventos.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(tblEventos);
        if (tblEventos.getColumnModel().getColumnCount() > 0) {
            tblEventos.getColumnModel().getColumn(1).setResizable(false);
            tblEventos.getColumnModel().getColumn(2).setResizable(false);
            tblEventos.getColumnModel().getColumn(3).setResizable(false);
            tblEventos.getColumnModel().getColumn(4).setResizable(false);
        }
        tblEventos.getAccessibleContext().setAccessibleName("");
        tblEventos.getAccessibleContext().setAccessibleDescription("");

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 170, 670, 440));

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 20));

        btnMiPerfil.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMiPerfil.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMiPerfilMouseClicked(evt);
            }
        });
        getContentPane().add(btnMiPerfil, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 20, 60, 20));

        btnVentaReventa.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnVentaReventa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnVentaReventaMouseClicked(evt);
            }
        });
        getContentPane().add(btnVentaReventa, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 120, 20));

        btnMisBoletos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnMisBoletos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnMisBoletosMouseClicked(evt);
            }
        });
        getContentPane().add(btnMisBoletos, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 20, 80, 20));

        btnEventos.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnEventos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEventosMouseClicked(evt);
            }
        });
        getContentPane().add(btnEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 20, 60, 20));

        txtCodigoCompra.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        getContentPane().add(txtCodigoCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 650, 30, 30));

        btnComprar.setText("Comprar");
        btnComprar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnComprarActionPerformed(evt);
            }
        });
        getContentPane().add(btnComprar, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 650, -1, -1));

        lblBotonCompra.setForeground(new java.awt.Color(51, 51, 51));
        lblBotonCompra.setText("Ingrese el codigo del boleto a comprar");
        getContentPane().add(lblBotonCompra, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 650, -1, -1));

        bgCatalogoEventos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgCatalogoEventos.png"))); // NOI18N
        getContentPane().add(bgCatalogoEventos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnMiPerfilMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMiPerfilMouseClicked
        FrmMiPerfilDP frmMiPerfilDP = new FrmMiPerfilDP(control, personasDTO);
        frmMiPerfilDP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnMiPerfilMouseClicked

    private void btnMisBoletosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnMisBoletosMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);

    }//GEN-LAST:event_btnMisBoletosMouseClicked

    private void btnVentaReventaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnVentaReventaMouseClicked
        FrmCompraVenta frmCompraVenta = new FrmCompraVenta(control, personasDTO);
        frmCompraVenta.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnVentaReventaMouseClicked

    private void btnEventosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEventosMouseClicked
        JOptionPane.showMessageDialog(this, "Boton en proceso", "En proceso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_btnEventosMouseClicked

    private void btnComprarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnComprarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnComprarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgCatalogoEventos;
    private javax.swing.JLabel btnClose;
    private javax.swing.JButton btnComprar;
    private javax.swing.JLabel btnEventos;
    private javax.swing.JLabel btnMiPerfil;
    private javax.swing.JLabel btnMisBoletos;
    private javax.swing.JLabel btnVentaReventa;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblBotonCompra;
    private javax.swing.JTable tblEventos;
    private javax.swing.JTextField txtCodigoCompra;
    // End of variables declaration//GEN-END:variables
}
