/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import java.text.SimpleDateFormat;
import java.util.Date;
import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.entidades.Personas;
import ticketwizard.persistencia.ConexionBD;
import ticketwizard.persistencia.PersonasDAO;

/**
 *
 * @author PC
 */
public class FrmCambiarDatos extends javax.swing.JFrame {

    ConexionBD conexionBD = new ConexionBD();
    private ControlInicio control;
    private PersonasDTO personasDTO;

    /**
     * Constructor que inicializa los atributos de la clase al valor de sus
     * parametros
     *
     * @param control
     * @param personasDTO
     */
    public FrmCambiarDatos(ControlInicio control, PersonasDTO personasDTO) {
        initComponents();
        this.control = control;
        this.personasDTO = personasDTO;
        agregarDatosActuales();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCalle = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtNumeroCasa = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtColonia = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        btnCerrar = new javax.swing.JPanel();
        btnCancelar = new javax.swing.JLabel();
        lblFormato = new javax.swing.JLabel();
        btnAceptar = new javax.swing.JLabel();
        bgCambiarDatos = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 750));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCalle, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, 30));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 460, 260, 30));
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 470, 160, 30));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 260, 30));
        getContentPane().add(txtNumeroCasa, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 370, 160, 30));
        getContentPane().add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 160, 30));
        getContentPane().add(txtColonia, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, 160, 30));
        getContentPane().add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, 30));

        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 20));

        btnCancelar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnCancelar.png"))); // NOI18N
        btnCancelar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCancelar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCancelarMouseClicked(evt);
            }
        });
        getContentPane().add(btnCancelar, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 560, 98, 40));

        lblFormato.setBackground(new java.awt.Color(0, 0, 0));
        lblFormato.setForeground(new java.awt.Color(0, 0, 0));
        lblFormato.setText("dd/mm/aaaa");
        getContentPane().add(lblFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 450, -1, -1));

        btnAceptar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAceptar.png"))); // NOI18N
        btnAceptar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAceptar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAceptarMouseClicked(evt);
            }
        });
        getContentPane().add(btnAceptar, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 560, 98, 40));

        bgCambiarDatos.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgCambiarDatos.png"))); // NOI18N
        getContentPane().add(bgCambiarDatos, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void agregarDatosActuales() {
        txtNombre.setText(personasDTO.getNombre());
        txtApellidoPaterno.setText(personasDTO.getApellidoPaterno());
        txtApellidoPaterno.setText(personasDTO.getApellidoMaterno());
        txtCalle.setText(personasDTO.getCalle());
        txtColonia.setText(personasDTO.getColonia());
        txtNumeroCasa.setText(personasDTO.getNumeroCasa());
        txtCorreo.setText(personasDTO.getCorreoElectronico());
    }

    private void btnAceptarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAceptarMouseClicked

        try {
            SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
            dateFormat.setLenient(false); // Evita fechas invalidas

            Personas personaNuevosDatos = new Personas();
            personaNuevosDatos.setNombre(txtNombre.getText());
            personaNuevosDatos.setApellidoMaterno(txtApellidoPaterno.getText());
            personaNuevosDatos.setApellidoPaterno(txtApellidoMaterno.getText());
            personaNuevosDatos.setCalle(txtCalle.getText());
            personaNuevosDatos.setColonia(txtColonia.getText());
            personaNuevosDatos.setNumeroCasa(txtNumeroCasa.getText());
            personaNuevosDatos.setCorreoElectronico(txtCorreo.getText());
            personaNuevosDatos.setFechaNacimiento(dateFormat.parse(txtFechaNacimiento.getText()));

            PersonasDAO cambiarDatosPersona = new PersonasDAO(conexionBD);
            cambiarDatosPersona.actualizarPerosnaPorID(personasDTO.getCodigoPersona(), personaNuevosDatos);

            FrmMiPerfilDP frmMiPerfilDP = new FrmMiPerfilDP(control, personasDTO);
            frmMiPerfilDP.setVisible(true);
            this.dispose();
        } catch (Exception e) {
            System.err.println("Ha ocurrido un error al cambiar los datos de la persona: " + e);
        }
    }//GEN-LAST:event_btnAceptarMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnCancelarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCancelarMouseClicked
        FrmMiPerfilDP frmMiPerfilDP = new FrmMiPerfilDP(control, personasDTO);
        frmMiPerfilDP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarMouseClicked

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmCambiarDatos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmCambiarDatos().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgCambiarDatos;
    private javax.swing.JLabel btnAceptar;
    private javax.swing.JLabel btnCancelar;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtCalle;
    private javax.swing.JTextField txtColonia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNumeroCasa;
    // End of variables declaration//GEN-END:variables
}
