/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.entidades.Personas;
import ticketwizard.persistencia.ConexionBD;
import ticketwizard.persistencia.PersonasDAO;

/**
 *
 * @author PC
 */
public class FrmInicioSesion extends javax.swing.JFrame {

    ConexionBD conexionBD = new ConexionBD();
    private final ControlInicio control;

    /**
     * Contstructor que inicializa los atributos de la clase con el valor de sus
     * parametros
     *
     * @param control Clase control
     */
    public FrmInicioSesion(ControlInicio control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtCorreo = new javax.swing.JTextField();
        txtContrasenia = new javax.swing.JPasswordField();
        btnLogin = new javax.swing.JLabel();
        btnRegistrarse = new javax.swing.JLabel();
        btnClose = new javax.swing.JPanel();
        bgLogin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 750));
        setUndecorated(true);
        setPreferredSize(new java.awt.Dimension(950, 750));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 330, 260, 30));
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 390, 260, 30));

        btnLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnLogin.png"))); // NOI18N
        btnLogin.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnLogin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnLoginMouseClicked(evt);
            }
        });
        getContentPane().add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 470, 98, 40));

        btnRegistrarse.setForeground(new java.awt.Color(51, 51, 51));
        btnRegistrarse.setText("Registrarse");
        btnRegistrarse.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrarse.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarseMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrarse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 530, -1, -1));

        btnClose.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnClose.setOpaque(false);
        btnClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCloseMouseClicked(evt);
            }
        });
        getContentPane().add(btnClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 20));

        bgLogin.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgLogin.png"))); // NOI18N
        getContentPane().add(bgLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnLoginMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnLoginMouseClicked
        try {
            PersonasDAO personaDAO = new PersonasDAO(conexionBD);
//            personaDAO.iniciarSesion(txtCorreo.getText(), txtContrasenia.getText());

            Personas persona = personaDAO.iniciarSesion(txtCorreo.getText(), txtContrasenia.getText());

            PersonasDTO personaDTO = new PersonasDTO(persona.getNombre(),
                    persona.getApellidoPaterno(), persona.getApellidoMaterno(),
                    persona.getCorreoElectronico(), persona.getContrasenia(),
                    persona.getFechaNacimiento(), persona.getCalle(),
                    persona.getColonia(), persona.getNumeroCasa());

            FrmCatalogoEventos frmCatalogoEventos = new FrmCatalogoEventos(control, personaDTO);
            frmCatalogoEventos.setVisible(true);
            this.dispose();

        } catch (Exception ex) {
            System.err.println("Ha ocurrido un error inesperado: " + ex);
        }
    }//GEN-LAST:event_btnLoginMouseClicked

    private void btnCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCloseMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCloseMouseClicked

    private void btnRegistrarseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarseMouseClicked
        FrmRegistro frmRegistro = new FrmRegistro(control);
        frmRegistro.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnRegistrarseMouseClicked

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmInicioSesion.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmInicioSesion().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgLogin;
    private javax.swing.JPanel btnClose;
    private javax.swing.JLabel btnLogin;
    private javax.swing.JLabel btnRegistrarse;
    private javax.swing.JPasswordField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    // End of variables declaration//GEN-END:variables
}
