/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;

/**
 *
 * @author PC
 */
public class FrmMiPerfilSaldo extends javax.swing.JFrame {

    private final ControlInicio control;
    private final PersonasDTO personasDTO;

    /**
     * Constructor que inicializa los atributos de la clase con el valor de los
     * parametros
     *
     * @param control Clase control
     * @param personasDTO Persona que haya iniciado sesion
     */
    public FrmMiPerfilSaldo(ControlInicio control, PersonasDTO personasDTO) {
        initComponents();
        this.control = control;
        this.personasDTO = personasDTO;
        mostrarSaldo();
    }

    private void mostrarSaldo() {
        lblSaldo.setText(Double.toString(personasDTO.getSaldo()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblMoney = new javax.swing.JLabel();
        lblSaldo = new javax.swing.JLabel();
        btnAgregarSaldo = new javax.swing.JLabel();
        btnDatosPersonales = new javax.swing.JPanel();
        btnCerrar = new javax.swing.JPanel();
        bgMiPerfilSaldo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(950, 750));
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblMoney.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        lblMoney.setForeground(new java.awt.Color(51, 51, 51));
        lblMoney.setText("$");
        getContentPane().add(lblMoney, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 210, 40, 70));

        lblSaldo.setFont(new java.awt.Font("Segoe UI", 1, 64)); // NOI18N
        lblSaldo.setForeground(new java.awt.Color(51, 51, 51));
        lblSaldo.setText("9999999.99");
        getContentPane().add(lblSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 210, 360, 70));

        btnAgregarSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnAgregarSaldo.png"))); // NOI18N
        btnAgregarSaldo.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnAgregarSaldo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnAgregarSaldoMouseClicked(evt);
            }
        });
        getContentPane().add(btnAgregarSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 300, 98, 40));

        btnDatosPersonales.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnDatosPersonales.setOpaque(false);
        btnDatosPersonales.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnDatosPersonalesMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnDatosPersonalesLayout = new javax.swing.GroupLayout(btnDatosPersonales);
        btnDatosPersonales.setLayout(btnDatosPersonalesLayout);
        btnDatosPersonalesLayout.setHorizontalGroup(
            btnDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 150, Short.MAX_VALUE)
        );
        btnDatosPersonalesLayout.setVerticalGroup(
            btnDatosPersonalesLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 40, Short.MAX_VALUE)
        );

        getContentPane().add(btnDatosPersonales, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 170, 150, 40));

        btnCerrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnCerrar.setOpaque(false);
        btnCerrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnCerrarMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout btnCerrarLayout = new javax.swing.GroupLayout(btnCerrar);
        btnCerrar.setLayout(btnCerrarLayout);
        btnCerrarLayout.setHorizontalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        btnCerrarLayout.setVerticalGroup(
            btnCerrarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );

        getContentPane().add(btnCerrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 10, 20, 20));

        bgMiPerfilSaldo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgMiPerfilSaldo.png"))); // NOI18N
        getContentPane().add(bgMiPerfilSaldo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarSaldoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnAgregarSaldoMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAgregarSaldoMouseClicked

    private void btnCerrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCerrarMouseClicked
        this.dispose();
    }//GEN-LAST:event_btnCerrarMouseClicked

    private void btnDatosPersonalesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnDatosPersonalesMouseClicked
        FrmMiPerfilDP frmMiPerfilDP = new FrmMiPerfilDP(control, personasDTO);
        frmMiPerfilDP.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnDatosPersonalesMouseClicked

//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmMiPerfilSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmMiPerfilSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmMiPerfilSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmMiPerfilSaldo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmMiPerfilSaldo().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgMiPerfilSaldo;
    private javax.swing.JLabel btnAgregarSaldo;
    private javax.swing.JPanel btnCerrar;
    private javax.swing.JPanel btnDatosPersonales;
    private javax.swing.JLabel lblMoney;
    private javax.swing.JLabel lblSaldo;
    // End of variables declaration//GEN-END:variables
}
