/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ticketwizard.presentacion;

import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JOptionPane;
import ticketwizard.control.ControlInicio;
import ticketwizard.dtos.PersonasDTO;
import ticketwizard.entidades.Personas;
import ticketwizard.persistencia.ConexionBD;
import ticketwizard.persistencia.PersonasDAO;

/**
 *
 * @author PC
 */
public class FrmRegistro extends javax.swing.JFrame {

    ConexionBD conexionBD = new ConexionBD();
    private final ControlInicio control;

    /**
     * Creates new form FrmRegistro
     */
    public FrmRegistro(ControlInicio control) {
        initComponents();
        this.control = control;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtContrasenia = new javax.swing.JTextField();
        txtDireccion = new javax.swing.JTextField();
        txtCorreo = new javax.swing.JTextField();
        txtFechaNacimiento = new javax.swing.JTextField();
        txtNombre = new javax.swing.JTextField();
        txtApellidoMaterno = new javax.swing.JTextField();
        txtApellidoPaterno = new javax.swing.JTextField();
        lblFormato = new javax.swing.JLabel();
        btnRegistrar = new javax.swing.JLabel();
        bgRegistro = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        setResizable(false);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        getContentPane().add(txtContrasenia, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 510, 260, 30));
        getContentPane().add(txtDireccion, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 370, 260, 30));
        getContentPane().add(txtCorreo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 450, 260, 30));
        getContentPane().add(txtFechaNacimiento, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 390, 160, 30));
        getContentPane().add(txtNombre, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 300, 260, 30));
        getContentPane().add(txtApellidoMaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 300, 160, 30));
        getContentPane().add(txtApellidoPaterno, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 300, 160, 30));

        lblFormato.setBackground(new java.awt.Color(0, 0, 0));
        lblFormato.setForeground(new java.awt.Color(0, 0, 0));
        lblFormato.setText("dd/mm/aaaa");
        getContentPane().add(lblFormato, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 370, -1, -1));

        btnRegistrar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/btnRegistrar.png"))); // NOI18N
        btnRegistrar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        btnRegistrar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnRegistrarMouseClicked(evt);
            }
        });
        getContentPane().add(btnRegistrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 620, 98, 40));

        bgRegistro.setIcon(new javax.swing.ImageIcon(getClass().getResource("/bgRegistro.png"))); // NOI18N
        getContentPane().add(bgRegistro, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 950, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnRegistrarMouseClicked

        SimpleDateFormat dateFormat = new SimpleDateFormat("dd/MM/yyyy");
        dateFormat.setLenient(false); // Evita fechas invalidas

        try {
            String nombre = txtNombre.getText();
            String apellidoPaterno = txtApellidoPaterno.getText();
            String apellidoMaterno = txtApellidoMaterno.getText();
            String direccion = txtDireccion.getText();
            Date fechaNacimiento = dateFormat.parse(txtFechaNacimiento.getText());
            String correo = txtCorreo.getText();
            String contrasenia = txtContrasenia.getText();

            Personas persona = new Personas(nombre, apellidoPaterno,
                    apellidoMaterno, correo, contrasenia,
                    fechaNacimiento, direccion);

            PersonasDTO personaDTO = new PersonasDTO(persona.getNombre(),
                    persona.getApellidoPaterno(), persona.getApellidoMaterno(),
                    persona.getCorreoElectronico(), persona.getContrasenia(),
                    persona.getFechaNacimiento(), persona.getDireccion());

            PersonasDAO personasDAO = new PersonasDAO(conexionBD);

            personasDAO.agregarPersona(personaDTO);

            JOptionPane.showMessageDialog(this, "Se ha registrado correctamente", "Aviso", JOptionPane.INFORMATION_MESSAGE);

            FrmInicioSesion frmInicioSesion = new FrmInicioSesion(control);
            frmInicioSesion.setVisible(true);
            this.dispose();
        } catch (ParseException ex) {
            System.err.println("Ocurrio un error al registrar el usuario: " + ex);
        }


    }//GEN-LAST:event_btnRegistrarMouseClicked

    /**
     * @param args the command line arguments
     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(FrmRegistro.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new FrmRegistro().setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel bgRegistro;
    private javax.swing.JLabel btnRegistrar;
    private javax.swing.JLabel lblFormato;
    private javax.swing.JTextField txtApellidoMaterno;
    private javax.swing.JTextField txtApellidoPaterno;
    private javax.swing.JTextField txtContrasenia;
    private javax.swing.JTextField txtCorreo;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtFechaNacimiento;
    private javax.swing.JTextField txtNombre;
    // End of variables declaration//GEN-END:variables
}
